services:
  bot:
    build:
      context: .
      dockerfile: project/bot/Dockerfile
    env_file:
      - .env
    volumes:
      - /home/danil/users.db:/app/users.db

  flask_webhook:
    build:
      context: .
      dockerfile: project/flask_webhook/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /home/danil/users.db:/app/users.db