services:
  bot:
    build:
      context: /home/danil/
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    volumes:
      - /home/danil/users.db:/app/users.db

  flask_webhook:
    build:
      context: /home/danil/
      dockerfile: flask_webhook/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /home/danil/users.db:/app/users.db