name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .env file
      run: |
        cd project
        echo "YOUR_ENV_VAR=value" > .env
        # Добавьте остальные переменные, если нужно

    - name: Build Docker images
      run: |
        cd project
        docker compose build

    - name: Start containers
      run: |
        cd project
        docker compose up -d

    - name: Wait for services to be ready
      run: sleep 10

    - name: Wait for Flask webhook service
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:8000/; then
            exit 0
          fi
          sleep 2
        done
        echo "Service did not start in time" >&2
        docker ps
        exit 1

    - name: Shutdown containers
      run: |
        cd project
        docker compose down