name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#
#      - name: Ensure users.db exists
#        run: |
#          if [ ! -f users.db ]; then
#            touch users.db
#          fi
#      - name: Set up Docker Build
#        uses: docker/setup-buildx-action@v2
#
#      - name: Create .env file
#        working-directory: ./
#        run: |
#          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
#          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env
#          echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> .env
#          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
#
#      - name: Build Docker images
#        working-directory: ./project
#        run: docker compose build
#
#      - name: Start containers
#        working-directory: ./project
#        run: docker compose up -d
#
#      - name: Wait for services to be ready
#        run: sleep 10
#
#      - name: Show docker compose ps
#        working-directory: ./project
#        run: docker compose ps
#
#      - name: Show docker compose logs
#        working-directory: ./project
#        run: docker compose logs
#
#      - name: Wait for Flask webhook service
#        working-directory: ./project
#        run: |
#          for i in {1..30}}; do
#            if curl -f http://localhost:8000/health; then
#              exit 0
#            fi
#            sleep 2
#          done
#          echo "Service did not start in time" >&2
#          docker ps
#          exit 1
#
#      - name: Shutdown containers
#        working-directory: ./project
#        run: docker compose down
  deploy:
    needs: build-and-test
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Run deploy script
        working-directory: ./project
        run: bash ./deploy.sh

